const projects = [
    {
        name: "CodeMe",
        description: "Search engine developed to efficiently find relevant code snippets and discussions built using the StackOverflow dataset. Employs advanced information retrieval techniques across 59 million posts",
        externalLink: "./portfolio",
        date: "2025",
        image: "/src/assets/CodeMe.webp",
        technologies: ["Python", "React", "PostgreSQL"],
        githubLink: "https://github.com/Sean-Leishman/CodeMe",
        isFinished: true,
    },
    {
        name: "PairwiseTurnGPT",
        description: "A timing-aware lexical-only turn-taking model developed and evaluated as part of my undergraduate dissertation and a subsequent publication at SemDial. Uses a dual-stream transformer model",
        link: "./portfolio",
        date: "2023-2025",
        image: "/src/assets/pairwise_turngpt.webp",
        externalLink: "https://www.semdial.org/anthology/papers/Z/Z24/Z24-3002/",
        technologies: ["Python", "Torch"],
        githubLink: "https://github.com/Sean-Leishman/PairwiseTurnGPT",
        isFinished: true,
    },
    {
        name: "Portfolio v2",
        description: "Redesign of my personal portfolio website. Designed to be more visually appealing and minimalistic while showing off my skills and projects.",
        externalLink: "",
        blogLink: "",
        date: "2025",
        image: "/src/assets/portfolio-v2.webp",
        technologies: ["Typescript", "React"],
        githubLink: "https://github.com/Sean-Leishman/portfolio-2025",
        isFinished: true,
    },
    {
        name: "Portfolio v1",
        description: "Original design of my personal portfolio webiste. Features a unique particle swarm visualisations in a single web page.",
        link: "./portfolio",
        date: "2023",
        image: "/src/assets/Portfolio.webp",
        technologies: ["Typescript", "three.js"],
        githubLink: "https://github.com/Sean-Leishman/portfolio",
        isFinished: true,
    },
    {
        name: "Turtle Chess",
        description: "Chess engine built using Python. Implements a basic minimax algorithm with alpha-beta pruning and a simple evaluation function. Features a graphical interface built using PyGame.",
        externalLink: "",
        blogLink: "/posts/TurtleChess: Adventures in Chess Engines/2023-06-24",
        date: "2022",
        image: "/src/assets/chess.webp",
        technologies: ["Python", "Pygame"],
        githubLink: "https://github.com/Sean-Leishman/turtle-chess",
        isFinished: true,
    },
    {
        name: "FlapRL",
        description: "Reinforcement Learning agent for Flappy Bird. Uses the NEAT algorithm to train a neural network to play the game. The agent learns to play the game by interacting with the environment and receiving rewards based on its performance.",
        externalLink: "",
        blogLink: "",
        date: "2022",
        image: "/src/assets/FlappyBirdRL.webp",
        technologies: ["TypeScript", "RL"],
        githubLink: "https://github.com/Sean-Leishman/flap-rl",
        isFinished: true,
    },
    {
        name: "Orchy",
        description: "Hobby Interpreter (WIP) that follows the Crafting Interpreters book. It is a simple programming language that is designed to be easy to learn and use. It is built using C++",
        externalLink: "",
        blogLink: "",
        date: "2023",
        image: "/src/assets/pdga/london_fog.webp",
        technologies: ["C++", "Programming Languages"],
        githubLink: "https://github.com/Sean-Leishman/orchy",
        isFinished: true,
    },
    {
        name: "Pathtracer",
        description: "A pathtracer built using C++ using the principles of physically based rendering. It simulates the way light interacts with surfaces to create realistic images and can support complex materials and lighting effects.",
        externalLink: "",
        blogLink: "",
        date: "2023",
        image: "/src/assets/Raytracer.webp",
        technologies: ["C++", "Graphics"],
        githubLink: "https://github.com/Sean-Leishman/raucous-wart",
        isFinished: true,
    },
    {
        name: "Film Wizard",
        description: "QA chatbot for film recommendations. Uses NLP techniques to understand user queries and provide relevant film suggestions. Built using Python",
        externalLink: "",
        blogLink: "",
        date: "2022",
        image: "/src/assets/pdga/de_la_poste.webp",
        technologies: ["Python", "NLP"],
        githubLink: "https://github.com/Sean-Leishman/film-wizard",
        isFinished: true,
    },
    {
        name: "StockTrend",
        description: "Full stack project that incorperates streamed data from the Twitter API and analyses sentiment in individual tweets in order to determine the overall sentiment in a certain stock",
        externalLink: "",
        blogLink: "/posts/StockTrend:%20 Unveiling the Power of Twitter Data/2023-06-20",
        date: "2022",
        image: "/src/assets/stocktrend.webp",
        technologies: ["Svelte", "AWS"],
        githubLink: "https://github.com/Sean-Leishman/stocktrend",
        isFinished: true,
    },
    {
        name: "GyroSound",
        description: "A mobile application that allows users to play music using their device's gyroscope and other sensors. The user uses their device control the playback of music, allowing for a unique and interactive experience.",
        externalLink: "",
        blogLink: "/posts/GyroSound: Handheld Music Playing/2023-07-16",
        date: "2023",
        image: "/src/assets/gyroSystem.webp",
        technologies: ["Android", "Kotlin"],
        githubLink: "https://github.com/Sean-Leishman/gyro-sound",
        isFinished: true,
    },
    {
        name: "NextStop",
        description: "A simulation and analysis of the Singapore MRT system. It uses a custom-built simulation engine to model the movement of trains and passengers, allowing for analysis of the system's performance and efficiency.",
        externalLink: "",
        blogLink: "",
        date: "2023",
        image: "/src/assets/next-stop.webp",
        technologies: ["Python"],
        githubLink: "https://github.com/Sean-Leishman/next-stop",
        isFinished: true,
    },
    {
        name: "Et Tu UV",
        description: "A wearable device that measures UV exposure and provides feedback to the user. It is designed to help users manage their UV exposure and reduce the risk of skin damage.",
        externalLink: "",
        blogLink: "/posts/Et Tu UV: Designing Wearables/2023-07-03",
        date: "2022",
        image: "/src/assets/et-tu-uv.webp",
        technologies: ["Arduino", "IoT", "Python"],
        githubLink: "https://github.com/Sean-Leishman/et-tu-uv",
        isFinished: true,
    },
    {
        name: "Path Finding Algorithm Visualiser",
        description: "A web application that visualises various path finding algorithms such as A* and Dijkstra's algorithm. It allows users to interactively explore how these algorithms work and compare their performance.",
        externalLink: "https://sean-leishman.github.io/path-finding-algorithm-visualiser/",
        blogLink: "",
        date: "2021",
        image: "/src/assets/pf.webp",
        technologies: ["JavaScript", "p5.js"],
        githubLink: "https://github.com/Sean-Leishman/path-finding-algorithm-visualiser",
        isFinished: true,
    },
    {
        name: "Sort Algorithm Visualiser",
        description: "A web application that visualises various sorting algorithms such as Bubble Sort and Merge Sort. It allows users to interactively explore how these algorithms work and compare their performance.",
        externalLink: "",
        blogLink: "",
        date: "2020",
        image: "/src/assets/sort-algorithm-2.webp",
        technologies: ["JavaScript", "React"],
        githubLink: "https://github.com/Sean-Leishman/sort-algorithm-visualizer",
        isFinished: true,
    }
]

export default function getProjects() {
    return projects;
}
